gestioci/apps/facturacio/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns(

    'gestioci.apps.facturacio.views',

    url(r'^llistat_quotes_trimestrals/$', 'llistat_quotes_trimestrals', name='llistat_quotes_trimestrals'),

    url(r'^editar_factura/(?P<id_factura>\d+)$',        'editar_factura',        name='editar_factura'),

    url(r'^crear_factura_emesa/$',                      'crear_factura_emesa',   name='crear_factura_emesa'),
    url(r'^crear_factura_emesa/(?P<id_client>\d+)$',    'crear_factura_emesa',   name='crear_factura_emesa'),
    url(r'^editar_factura_emesa/(?P<id_factura>\d+)$',  'editar_factura_emesa',  name='editar_factura_emesa'),

    url(r'^crear_factura_rebuda/$',                     'crear_factura_rebuda',  name='crear_factura_rebuda'),
    url(r'^crear_factura_rebuda/(?P<id_factura>\d+)$',  'crear_factura_rebuda',  name='crear_factura_rebuda'),
    url(r'^editar_factura_rebuda/(?P<id_factura>\d+)$', 'editar_factura_rebuda', name='editar_factura_rebuda'),

)

gestioci/apps/inici/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'gestioci.apps.inici.views',

    url(r'^/?$',           'index',      name='index'),
    url(r'^style-guide/$', 'styleguide', name='styleguide'),
)

gestioci/apps/socies/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'gestioci.apps.socies.views',
    url(r'^cerca_persones/$', 'cerca_persones', name='cerca_persones'),
)

gestioci/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = patterns(
    '',

    # Default Django Auth
    # https://docs.djangoproject.com/en/1.8/topics/auth/default/#built-in-auth-views
    url(r'^accounts/', include([
        url(r'^login/$', auth_views.login, name='login'),
        url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),

        url(r'^password/', include([
            url(r'^change/$', auth_views.password_change, name='password_change'),
            url(r'^change/done/$', auth_views.password_change_done, name='password_change_done'),

            url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
            url(r'^reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),
            url(r'^reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
            url(r'^reset/$', auth_views.password_reset, { 'html_email_template_name': 'registration/password_reset_email.html' }, name='password_reset'),
        ])),
    ])),


    # Apps
    url(r'^',             include('gestioci.apps.inici.urls', namespace='inici')),
    url(r'^socies/alta/', include('gestioci.apps.alta_socies.urls', namespace='alta_socies')),
    url(r'^socies/',      include('gestioci.apps.socies.urls', namespace='socies')),
    url(r'^facturacio/',  include('gestioci.apps.facturacio.urls', namespace='facturacio')),
    
    url(r'^admin/',       include(admin.site.urls)),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns(
        '',
        (
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

gestioci/apps/inici/models.py
from django.db import models

# Create your models here.

gestioci/apps/alta_socies/views.py
# coding=utf-8
import calendar
import json
from datetime import date, timedelta

from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.core.exceptions import SuspiciousOperation
from django.forms import modelformset_factory, formset_factory, SplitDateTimeWidget
from django.forms.models import modelform_factory
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.template import RequestContext
from django.utils import timezone
from django.conf import settings
from django.db.models import Count
from django.http import HttpResponse
from django.template import loader, Context
from django.contrib.auth.models import User

from .forms import GeneradorSessions, FormulariProjecte, FormulariDadesGeneralsProjecte, \
    FormulariDetallsMembreDeReferencia, FormulariAdrecaProjecteAutoocupat, \
    FormulariAltaProjecteAutoocupatSessioMoneda, FormulariAltaProjecteAutoocupatCessioUs, \
    FormulariAltaProjecteAutoocupatLloguer, FormulariAltresActivitatsProjecteAutoocupatFiraire, \
    FormulariAltresActivitatsProjecteAutoocupatNoFiraire, FormulariAltaConcessioActivitat, FormulariAltaAsseguranca, \
    FormulariAltaQuotes, FormulariFormaPagamentQuotesAutoocupat, FormulariCercaActualitzacioSeleccioPersones, \
    ForulariPas19, FormulariFotoProjecteAutoocupatFiraire
from gestioci.settings import auth_groups
from .models import SessioAlta, SessioAvaluacio, ProcesAltaAutoocupat, SessioAcollida, \
    PeticioConcessioActivitat, PeticioAsseguranca, SessioMoneda
from gestioci.apps.socies.models import Persona, AdrecaProjecteAutoocupat, HabilitatsContribucionsPersona, \
    Habilitat, ContribucioCIC, Activitat
from gestioci.apps.empreses.models import Cooperativa
from gestioci.formats import dow_names
from gestioci.thumbnails import create_thumbnail
from gestioci.apps.projectes.models import FotoProjecteAutoocupatFiraire, \
    ProjecteAutoocupat, PolissaAsseguranca
from gestioci.apps.alta_socies.utils import generate_task_list_pdf

@login_required
def rebutjar_proces_alta_autoocupat(request, proces_id):
    """
    Vista para rechazar un proceso de alta para
    un socio autoocupado
    """
    proces = ProcesAltaAutoocupat.objects.get(id=proces_id)
    proces.resolucio = 'rebutjat'
    proces.data_resolucio = timezone.localtime(timezone.now())
    proces.save()
    messages.error(request, "El projecte ha sigut rebutjat correctament")
    return redirect('inici:index')


def is_user_responsable_alta(user):
    """
    function that returns True when user belongs
    to RESPONSABLE_ALTA group
    """
    return user.groups.filter(name=auth_groups.RESPONSABLES_ALTA).exists()


class FilterResponsablesAltaMixin(object):
    """
    Mixin per filtrar la llista d'opcions al widget del camp "responsable_alta"
    de manera que només ofereix usuaris membres del grup RESPONSABLES_ALTA
    """
    def get_context_data(self, **kwargs):
        context = super(FilterResponsablesAltaMixin, self).get_context_data(**kwargs)
        context['form'].fields['responsable_alta'].queryset = User.objects.filter(
            groups__name=auth_groups.RESPONSABLES_ALTA)
        return context


def is_user_exporter(user):
    """
    function that returns True when user belongs
    to EXPORTADORES group
    """
    return user.groups.filter(name=auth_groups.EXPORTADORES).exists()


@login_required
@user_passes_test(is_user_exporter)
def exportar_a_csv(request):
    """ 
    Vista per exportar els processos d'alta de projecte
    autoocupat en format CSV ("cap al transversal")
    """

    d = timezone.localtime(timezone.now()).date().isoformat()
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="projectes-%s.csv"' % d

    queryset = ProcesAltaAutoocupat.objects.all()

    csv_data = []
    for p in queryset:
        projecte = []
        projecte += [
            p.data_resolucio,
            p.compte_CES_assignat,
            p.cooperativa_assignada,
            p.email,
            p.telefon]
        if p.adreces.first() is not None:
            projecte += [
                p.adreces.first().adreca,
                p.adreces.first().codi_postal,
                p.adreces.first().poblacio,
                p.adreces.first().comarca]
        else:
            projecte += [
                None,
                None,
                None,
                None]
        if p.membres_de_referencia.first() is not None:
            projecte += [
                p.membres_de_referencia.first().nom,
                p.membres_de_referencia.first().cognom1 +
                " " + p.membres_de_referencia.first().cognom2,
                p.membres_de_referencia.first().dni]
        else:
            projecte += [
                None,
                None,
                None]
        projecte.append(p.individual)
        projecte.append(p.pas)
        projecte = ['' if word is None else word for word in projecte]
        csv_data.append(projecte)
    """
    # How it should be when all projects are accepted
    csv_data = [[p.data_resolucio,
                 p.compte_CES_assignat,
                 p.compte_CES_assignat,
                 p.cooperativa_assignada,
                 p.email,
                 p.telefon,
                 p.adreces.first().adreca,
                 p.adreces.first().codi_postal,
                 p.adreces.first().poblacio,
                 p.adreces.first().comarca,
                 p.membres_de_referencia.objects.first().nom,
                 p.membres_de_referencia.objects.first().cognom1 +
                 " " + p.membres_de_referencia.objects.first().cognom2,
                 p.membres_de_referencia.objects.first().dni,
                 p.individual]
                for p in queryset]
    """
    t = loader.get_template("alta_socies/export.txt")
    c = Context({'data': csv_data})
    response.write(t.render(c))
    return response


class ProcesAltaAutoocupatDetailView(DetailView):
    """Vista resum per visualitzar els detalls
       d'un procés d'alta quan no es vol editar,
       o quan no es té permís per editar-lo
       p. ex. quan el vol consultar algú que no
       n'és el responsable d'alta"""

    model = ProcesAltaAutoocupat
    context_object_name = 'proces'
    template_name = 'alta_socies/autoocupat/detail.html'

    @method_decorator(login_required)
    @method_decorator(user_passes_test(is_user_responsable_alta))
    def dispatch(self, *args, **kwargs):
        return super(ProcesAltaAutoocupatDetailView, self).dispatch(*args, **kwargs)


class SessioAcollidaUpdateView(SuccessMessageMixin, FilterResponsablesAltaMixin, UpdateView):
    """Vista per editar les sessions d'acollida"""

    model = SessioAcollida
    template_name = 'alta_socies/formulari_sessio.html'
    success_url = '/'
    success_message = "La sessió d'acollida s'ha actualitzat correctament"
    title = u"Editar sessió d'acollida"
    action_label = u"Desar"

    @method_decorator(login_required)
    @method_decorator(user_passes_test(is_user_responsable_alta))
    def dispatch(self, *args, **kwargs):
        return super(SessioAcollidaUpdateView, self).dispatch(*args, **kwargs)


class SessioAcollidaListView(ListView):
    """Vista per llistar les sessions d'acollida"""

    context_object_name = 'sessions'
    queryset = SessioAcollida.objects.order_by('-data')
    template_name = 'alta_socies/llistat_sessions.html'

    title = u"Llistat de sessions d'acollida"
    edit_url = 'alta_socies:editar_sessio_acollida'

    @method_decorator(login_required)
    @method_decorator(user_passes_test(is_user_responsable_alta))
    def dispatch(self, *args, **kwargs):
        return super(SessioAcollidaListView, self).dispatch(*args, **kwargs)


class SessioAcollidaCreateView(SuccessMessageMixin, FilterResponsablesAltaMixin, CreateView):
    """Vista per crear sessions d'acollida"""

    model = SessioAcollida
    template_name = 'alta_socies/formulari_sessio.html'
    form_class = modelform_factory(SessioAcollida,
                                   widgets={"data": SplitDateTimeWidget},
                                   fields=['data', 'ubicacio', 'duracio', 'responsable_alta'])
    success_url = '/'
    success_message = "La sessió d'acollida ha sigut creada correctament"
    title = u"Crear sessió d'acollida"
    action_label = u"Crear"

    @method_decorator(login_required)
    @method_decorator(user_passes_test(is_user_responsable_alta))
    def dispatch(self, *args, **kwargs):
        return super(SessioAcollidaCreateView, self).dispatch(*args, **kwargs)


class SessioMonedaUpdateView(SuccessMessageMixin, FilterResponsablesAltaMixin, UpdateView):
    """Vista per editar les sessions de moneda social"""

    model = SessioMoneda
    template_name = 'alta_socies/formulari_sessio.html'
    success_url = '/'
    success_message = "La sessió de moneda social s'ha actualitzat correctament"
    title = u"Editar sessiò de moneda social"
    action_label = u"Desar"

    @method_decorator(login_required)
    @method_decorator(user_passes_test(is_user_responsable_alta))
    def dispatch(self, *args, **kwargs):
        return super(SessioMonedaUpdateView, self).dispatch(*args, **kwargs)


class SessioMonedaListView(ListView):
    """Vista per llistar les sessions de moneda social"""

    context_object_name = 'sessions'
    queryset = SessioMoneda.objects.order_by('-data')
    template_name = 'alta_socies/llistat_sessions.html'

    title = u"Llistat de sessions de moneda social"
    edit_url = 'alta_socies:editar_sessio_moneda'

    @method_decorator(login_required)

gestioci/apps/empreses/views.py
from django.shortcuts import render

# Create your views here.

gestioci/apps/inici/views.py
# coding=utf-8
from django.contrib import messages
from django.shortcuts import render


def index(request):
    return render(request, 'inici/index.html', {
        'page_title': u'Inici',
    })


def styleguide(request):
    from django import forms

    choice_list = (('', 'Select…'), ('foo', 'Foo'), ('bar', 'Bar'), ('baz', 'Baz'), ('qux', 'Qux'))

    class Form(forms.Form):
        name = forms.CharField(label='Nombre', max_length=100)
        email = forms.EmailField(label='Email', required=False, help_text='This is a help text.')
        boolean = forms.BooleanField(label='Boolean', required=False)
        accept = forms.BooleanField(label='Boolean')
        choices = forms.ChoiceField(label='Choices', choices=choice_list)
        radiuses = forms.ChoiceField(label='Radius', choices=choice_list, widget=forms.RadioSelect)
        multiple = forms.MultipleChoiceField(label='Multiple Choices', choices=choice_list, initial=('foo', 'baz'))
        multicheck = forms.MultipleChoiceField(label='Checkboxes', choices=choice_list, widget=forms.CheckboxSelectMultiple)
        date = forms.DateField(label='Date', widget=forms.DateInput, initial='2015-05-01')
        time = forms.TimeField(label='Time', widget=forms.TimeInput, initial='15:20')
        datetime = forms.DateTimeField(label='Datetime', widget=forms.SplitDateTimeWidget)

    messages.info(request, 'Three credits remain in your account.')
    messages.success(request, 'Profile details updated.')
    messages.warning(request, 'Your account expires in three days.')
    messages.error(request, 'Document deleted.')

    return render(request, 'inici/styleguide.html', {
        'forms': {
            'A':               Form(),
            'B (POST Errors)': Form(request.POST)
        },
        'page_title': u'Style Guide',
    })

gestioci/apps/projectes/views.py
from django.shortcuts import render

# Create your views here.

gestioci/apps/socies/views.py
# coding=utf-8
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseBadRequest
from cercadors import cerca_difusa_de_persones
import json


@login_required
def cerca_persones(request):

    if request.method == 'POST':

        parametres_de_la_cerca = {}
        for key in ['nom', 'cognom1', 'cognom2', 'pseudonim', 'email', 'telefon', 'dni']:
            value = request.POST.get(key, None)
            if value:
                value = value.strip()
                if len(value):
                    parametres_de_la_cerca[key] = value

        if parametres_de_la_cerca:

            coincidencies = cerca_difusa_de_persones(**parametres_de_la_cerca)

            result_array = []
            for coincidencia in coincidencies:
                persona_dict = {}
                persona = coincidencia['persona']
                persona_dict['id'] = persona.id
                persona_dict['punts'] = coincidencia['punts']
                persona_dict['text'] = persona.tots_els_detalls
                persona_dict['nom'] = persona.nom
                persona_dict['cognom1'] = persona.cognom1
                persona_dict['cognom2'] = persona.cognom2
                persona_dict['pseudonim'] = persona.pseudonim
                persona_dict['email'] = persona.email
                persona_dict['telefon'] = persona.telefon
                persona_dict['dni'] = persona.dni
                persona_dict['tipus_document_dni'] = persona.tipus_document_dni
                persona_dict['compte_integralces'] = persona.compte_integralces

                result_array.append(persona_dict)

            result = json.dumps(result_array)
        else:
            result = json.dumps([])

    else:
        return HttpResponseBadRequest(u"Què mireu? :)")

    return HttpResponse(result, content_type='application/json')

gestioci/templates/base.html
{% load gci_tags %}
{% load staticfiles %}

{% spaceless %}
<!DOCTYPE html>
<html lang="ca" class="env-{{ ENV }}">
    <head>
        <meta charset="utf-8">
        <meta name="version" content="{{ VERSION }}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>GestioCI{% if page_title %} – {{ page_title }}{% endif %}</title>
        <link rel="stylesheet" href="{% static "css/gestioci.css" %}"/>
        <script src="{% static "js/gestioci-head.js" %}"></script>
    </head>
    <body>
        {% block menu %}{% endblock %}

        {% if messages %}
            <div class="row messages">
                {% for message in messages %}
                    <div data-alert class="alert-box radius {% if message.tags %}{{ message.tags }}{% endif %}">
                        {% if 'info' in message.tags %}<i class="fa fa-info-circle fa-fw"></i>{% endif %}
                        {% if 'success' in message.tags %}<i class="fa fa-check fa-fw"></i>{% endif %}
                        {% if 'warning' in message.tags %}<i class="fa fa-exclamation-triangle fa-fw"></i>{% endif %}
                        {% if 'alert' in message.tags %}<i class="fa fa-exclamation fa-fw"></i>{% endif %}
                        {{ message }}
                        <a href="#" class="close">&times;</a>
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        {% block body %}{% endblock %}

        <div class="row footer">
            <div class="medium-12 columns">
                <p class="small">
                    GestioCI {{ VERSION }}{% if ENV != 'production' %} ({{ ENV }}){% endif %}, CIC 2014–{% now "Y" %}
                    {% if DEBUG %}
                        <br/><a href="{% url 'inici:styleguide' %}">CSS Style Guide</a>
                    {% endif %}
                </p>
            </div>
        </div>

        <script src="{% static "js/gestioci.js" %}"></script>
        {% block javascript %}{% endblock %}
    </div>
    </body>
</html>
{% endspaceless %}

gestioci/templates/blank.html
{% extends "base.html" %}

{% block body %}
    <div class="row">
        <div class="medium-12 columns">
            {% block content %}{% endblock %}
        </div>
    </div>
{% endblock %}

gestioci/templates/gci.html
{% load gci_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head lang="ca">
        <meta charset="UTF-8">
        <title>[GestioCI]{% if page_title %} {{ page_title }}{% endif %}</title>
        <link rel="stylesheet" href="{% static "css/old.css" %}" ></link>
    </head>

    <body>
        <table class="principal-capcalera">
            <tr>
                <td id="logo">
                    <a href="{% url "inici:index" %}">GestioCI</a>
                </td>
                <td id="titol_a_capcalera">
                    {% block titol_a_capcalera %}{% endblock %}
                </td>
                <td id="controls_sessio">
                    {% if user.is_authenticated %}{{ user.first_name }}&nbsp;{{ user.last_name }}&nbsp;|&nbsp;<a href="{% url "logout" %}">desconnectar</a>{% endif %}
                </td>
            </tr>
        </table>

        <div id="principal_contingut">
            {% block main %}{% endblock %}
        </div>

        <div id="principal-peu">GestioCI versió {% gci_release %} &mdash; CICIC 2014-2015</div>
    </body>
</html>

gestioci/templates/layout.html
{% extends "base.html" %}

{% block menu %}
    <div class="row">
        <div class="medium-12 columns content menu">
            <div class="wrapper">
                <nav class="top-bar" data-topbar role="navigation">
                    <ul class="title-area">
                        <li class="name">
                            <h1><a href="{% url "inici:index" %}">GestioCI</a></h1>
                        </li>
                        <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
                    </ul>

                    <section class="top-bar-section">
                        <!-- Right Nav Section -->
                        <ul class="right">
                            {% if not user.is_authenticated %}
                                <li class="login">
                                    <a href="{% url "login" %}" class="radius button">
                                        <i class="fa fa-fw fa-sign-in"></i>
                                        Iniciar sessió
                                    </a>
                                </li>
                            {% endif %}
                            {% if user.is_authenticated %}
                                <li class="has-dropdown not-click">
                                    <a href="#">
                                        <i class="fa fa-fw fa-user"></i> {{ user.first_name }} {{ user.last_name }}
                                    </a>
                                    <ul class="dropdown">
                                        <li><a href="{% url "password_change" %}"><i class="fa fa-fw fa-key"></i> Canviar contrasenya</a></li>
                                        <li><a href="{% url "logout" %}"><i class="fa fa-fw fa-sign-out"></i> Tancar sessió</a></li>
                                    </ul>
                                </li>
                            {% endif %}
                        </ul>

                        <!-- Left Nav Section -->
                        <ul class="left">
                            <li><a href="{% url "inici:index" %}">Inici</a></li>
                        </ul>
                    </section>
                </nav>
            </div>
        </div>
    </div>
{% endblock %}

{% block body %}
    {% block content %}{% endblock %}
{% endblock %}

gestioci/templates/simple.html
{% extends "layout.html" %}

{% block body %}
    <div class="row">
        <div class="medium-12 columns content">
            {% block content %}{% endblock %}
        </div>
    </div>
{% endblock %}