gestioci/apps/alta_socies/urls.py
from django.conf.urls import patterns, include, url

from .views import SessioMonedaListView, SessioMonedaCreateView
from .views import SessioAcollidaListView, SessioAcollidaCreateView, \
    SessioAcollidaUpdateView, SessioMonedaUpdateView
from .views import ProcesAltaAutoocupatDetailView

urlpatterns = patterns(

    'gestioci.apps.alta_socies.views',

    # -----------------
    # SOCIS AUTOOCUPATS
    # -----------------

    url(r'^rebutjar_proces_alta/(?P<proces_id>\d+)/$', 'rebutjar_proces_alta_autoocupat', name='rebutjar_proces'),

    url(r'^exportar_a_csv/$', 'exportar_a_csv', name='exportar_a_csv'),

    url(r'^autoocupat/resum/(?P<pk>\d+)/$', ProcesAltaAutoocupatDetailView.as_view(), name='resum_proces_alta_projecte_autoocupat'),

    url(r'^editar_sessio_moneda/(?P<pk>\d+)/$', SessioMonedaUpdateView.as_view(), name='editar_sessio_moneda'),

    url(r'^editar_sessio_acollida/(?P<pk>\d+)/$', SessioAcollidaUpdateView.as_view(), name='editar_sessio_acollida'),

    url(r'^llistat_sessio_acollida', SessioAcollidaListView.as_view(), name='llistat_sessio_acollida'),

    url(r'^crear_sessio_acollida', SessioAcollidaCreateView.as_view(), name='crear_sessio_acollida'),

    url(r'^llistat_sessio_moneda', SessioMonedaListView.as_view(), name='llistat_sessio_moneda'),

    url(r'^crear_sessio_moneda', SessioMonedaCreateView.as_view(), name='crear_sessio_moneda'),

    url(r'^generador_sessions/$',
        'generar_sessions',
        name='generador_sessions'),

    url(r'^sessions_del_mes/(?P<tipus>\w+)(/(?P<year>\d\d\d\d)/(?P<month>\d\d?))?$',
        'sessions_del_mes',
        name='sessions_del_mes'),

    url(r'^autoocupat/$',
        'proces_alta_projecte_autoocupat',
        name='proces_alta_projecte_autoocupat'),

    url(r'^autoocupat/(?P<id_proces>\d+)/$',
        'proces_alta_projecte_autoocupat',
        name='proces_alta_projecte_autoocupat'),

    url(r'^autoocupat/(?P<id_proces>\d+)/(?P<pas>\d+)/$',
        'proces_alta_projecte_autoocupat',
        name='proces_alta_projecte_autoocupat'),

    url(r'^autoocupat/llista-tasques/(?P<id_proces>\d+)/$',
        'proces_alta_projecte_autoocupat_llista_de_tasques',
        name='proces_alta_projecte_autoocupat-llista_de_tasques'),

    url(r'^autoocupat/llista-tasques/(?P<id_proces>\d+)/(?P<format>pdf|html)/$',
        'proces_alta_projecte_autoocupat_llista_de_tasques',
        name='proces_alta_projecte_autoocupat-llista_de_tasques'),

    url(r'^autoocupat/processos/(?P<estat>\w+)/$',
        'llistat_proces_alta_projecte_autoocupat',
        name='llistat_proces_alta_projecte_autoocupat'),

    url(r'^autoocupat/processos/(?P<estat>\w+)/tots$',
        'llistat_proces_alta_projecte_autoocupat', {'filtre_responsable': False},
        name='llistat_proces_alta_projecte_autoocupat-tots'),

    url(r'^autoocupat/control-qualitat/$',
        'llistat_proces_alta_projecte_autoocupat_revisio_descripcions',
        name='llistat_proces_alta_projecte_autoocupat_revisio_descripcions'),

    url(r'^estadistiques_proces_alta_projecte_autoocupat/?$',
        'estadistiques_proces_alta_projecte_autoocupat',
        name='estadistiques_proces_alta_projecte_autoocupat'),

    # -----------------
    # SOCIS COOPERATIUS
    # -----------------
    url(r'^cooperatiu/$', 'cooperatiu', name='cooperatiu'),
)

gestioci/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = patterns(
    '',

    # Default Django Auth
    # https://docs.djangoproject.com/en/1.8/topics/auth/default/#built-in-auth-views
    url(r'^accounts/', include([
        url(r'^login/$', auth_views.login, name='login'),
        url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),

        url(r'^password/', include([
            url(r'^change/$', auth_views.password_change, name='password_change'),
            url(r'^change/done/$', auth_views.password_change_done, name='password_change_done'),

            url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
            url(r'^reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),
            url(r'^reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
            url(r'^reset/$', auth_views.password_reset, { 'html_email_template_name': 'registration/password_reset_email.html' }, name='password_reset'),
        ])),
    ])),


    # Apps
    url(r'^',             include('gestioci.apps.inici.urls', namespace='inici')),
    url(r'^socies/alta/', include('gestioci.apps.alta_socies.urls', namespace='alta_socies')),
    url(r'^socies/',      include('gestioci.apps.socies.urls', namespace='socies')),
    url(r'^facturacio/',  include('gestioci.apps.facturacio.urls', namespace='facturacio')),
    
    url(r'^admin/',       include(admin.site.urls)),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns(
        '',
        (
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

gestioci/apps/projectes/models.py
# coding=utf-8
from django.db import models

from gestioci.apps.empreses.models import EmpresaAsseguradora, Cooperativa, Empresa
from gestioci.apps.socies.models import Persona, AdrecaProjecteAutoocupat, Activitat
from gestioci.apps.alta_socies.models import ProcesAltaAutoocupat, PeticioAsseguranca


class ProjecteAutoocupatManager(models.Manager):

    def create_projecte(self, proces):

        projecte = self.create(proces=proces)

        projecte.nom = proces.nom
        projecte.email = proces.email
        projecte.telefon = proces.telefon
        projecte.website = proces.website
        projecte.descripcio = proces.descripcio
        projecte.data_creacio = proces.data_resolucio
        projecte.tipus = proces.tipus
        projecte.individual = proces.individual
        projecte.es_paic = proces.es_paic
        projecte.te_comerc_electronic = proces.te_comerc_electronic
        projecte.mercat_virtual = proces.mercat_virtual
        projecte.te_productes_ecologics = proces.te_productes_ecologics
        projecte.tipus_parada_firaire = proces.tipus_parada_firaire
        projecte.expositors = proces.expositors
        projecte.compte_ces_assignat = proces.compte_CES_assignat
        projecte.iva_assignat = proces.iva_assignat
        projecte.quota_avancada_quantitat = proces.quota_avancada_quantitat
        projecte.quota_avancada_forma_pagament = proces.quota_avancada_forma_pagament

        projecte.cooperativa_assignada = proces.cooperativa_assignada

        for membre in proces.membres_de_referencia.all():
            projecte.membres_de_referencia.add(membre)
        for adreca in proces.adreces.all():
            projecte.adreces.add(adreca)
        for activitat in proces.altres_activitats.all():
            projecte.altres_activitats.add(activitat)
        for soci in proces.socies_afins_addicionals.all():
            projecte.socies_afins_addicionals.add(soci)

        projecte.socia_mentora = proces.socia_mentora

        projecte.save()

        return projecte


class ProjecteAutoocupat(models.Model):

    proces = models.OneToOneField(ProcesAltaAutoocupat, null=True, on_delete=models.SET_NULL)

    nom = models.CharField(max_length=256)
    email = models.EmailField()
    telefon = models.CharField(max_length=32)
    website = models.URLField(verbose_name=u"lloc web", null=True)
    descripcio = models.TextField(verbose_name=u"descripció", null=True)
    data_creacio = models.DateField(null=True)
    tipus = models.CharField(max_length=20)
    individual = models.CharField(max_length=16)
    es_paic = models.BooleanField(default=False)
    te_comerc_electronic = models.BooleanField(default=False)
    mercat_virtual = models.BooleanField(default=False)
    te_productes_ecologics = models.BooleanField(default=False)
    tipus_parada_firaire = models.CharField(max_length=16)
    expositors = models.BooleanField(default=False)
    compte_ces_assignat = models.CharField(max_length=16)
    iva_assignat = models.IntegerField(default=18)
    quota_avancada_quantitat = models.DecimalField(max_digits=8, decimal_places=2, null=True)
    quota_avancada_forma_pagament = models.CharField(max_length=6)

    cooperativa_assignada = models.ForeignKey(Cooperativa, null=True)

    membres_de_referencia = models.ManyToManyField(Persona,
                                                   related_name='projectes_autoocupats',
                                                   verbose_name=u"membres de referència")
    adreces = models.ManyToManyField(AdrecaProjecteAutoocupat,
                                     related_name='xxx_projecte_autoocupat')  # TODO remove when fixed upstream
    altres_activitats = models.ManyToManyField(Activitat, related_name='+',
                                               help_text=u"Altres activitats no vinculades a cap adreça")
    socies_afins_addicionals = models.ManyToManyField(Persona, related_name='+')

    socia_mentora = models.OneToOneField(Persona, null=True, related_name='+')

    objects = ProjecteAutoocupatManager()

    @staticmethod
    def _filtrar_queryset_factura_per_data(queryset, des_de, fins_a):
        """
        donat un queryset sobre el model Factura, retorna un nou queryset que exclou
        les factures que es troben fora del periode que indiquen les dates.
        :type queryset: django.db.models.query.QuerySet
        :param queryset: hauria de ser sobre el model Factura, o "derivats"
        :param des_de: data inicial del periode a seleccionar
        :param fins_a: data final del periode a seleccionar
        :return: queryset original modificat de manera que exclou factures amb data < "des_de" i > "fins_a"
        """
        if des_de:
            queryset = queryset.filter(data__gte=des_de)
        if fins_a:
            queryset = queryset.filter(data__lte=fins_a)
        return queryset

    def proveidors(self, des_de=None, fins_a=None):
        factures_rebudes = self.factura_set.filter(projecte=self)
        factures_rebudes = self._filtrar_queryset_factura_per_data(factures_rebudes, des_de, fins_a)
        llista_id_proveidors = factures_rebudes.values_list('proveidor', flat=True).distinct()
        return Empresa.objects.filter(id__in=llista_id_proveidors)

    def clients(self, des_de=None, fins_a=None):
        factures_emeses = self.factura_set.filter(projecte=self)
        factures_emeses = self._filtrar_queryset_factura_per_data(factures_emeses, des_de, fins_a)
        llista_id_clients = factures_emeses.values_list('client', flat=True).distinct()
        return Empresa.objects.filter(id__in=llista_id_clients)

    class Meta:
        verbose_name = u"projecte autoocupat"
        verbose_name_plural = u"projectes autoocupats"


class PolissaAssegurancaManager(models.Manager):

    def create_polissa(self, peticio, projecte):

        polissa = self.create(peticio=peticio, projecte_autoocupat=projecte)

        polissa.adreca = peticio.adreca
        polissa.activitat = peticio.activitat
        polissa.comentaris_avaluacio = peticio.comentaris_avaluacio
        polissa.companyia_asseguradora = peticio.companyia_asseguradora
        polissa.numero_polissa = peticio.numero_polissa
        polissa.data_inici_polissa = peticio.data_inici_polissa
        polissa.data_final_polissa = peticio.data_final_polissa
        polissa.import_polissa = peticio.import_polissa
        polissa.comentaris_alta = peticio.comentaris_alta

        polissa.save()

        return polissa


class PolissaAsseguranca(models.Model):

    peticio = models.OneToOneField(PeticioAsseguranca, null=True, on_delete=models.SET_NULL)

    adreca = models.ForeignKey(AdrecaProjecteAutoocupat, null=True)
    activitat = models.ForeignKey(Activitat, null=True)
    projecte_autoocupat = models.ForeignKey(ProjecteAutoocupat, related_name='polisses_asseguranca')
    comentaris_avaluacio = models.TextField(null=True)

    companyia_asseguradora = models.ForeignKey(EmpresaAsseguradora, null=True)
    numero_polissa = models.CharField(max_length=128, verbose_name=u"número de pòlissa")
    data_inici_polissa = models.DateField(null=True, verbose_name=u"data d'inici de la cobertura")
    data_final_polissa = models.DateField(null=True, verbose_name=u"data d'acabament de la cobertura")
    import_polissa = models.DecimalField(max_digits=8, decimal_places=2, null=True,
                                         verbose_name=u"import total periode cobertura")
    comentaris_alta = models.TextField(null=True)

    objects = PolissaAssegurancaManager()

    class Meta:
            verbose_name = u"pòlissa d'assegurança"
            verbose_name_plural = u"pòlisses d'assegurança"


class FotoProjecteAutoocupatFiraire(models.Model):

    projecte = models.ForeignKey(ProjecteAutoocupat, related_name='fotos_parada_firaire')
    nom = models.CharField(max_length=256)
    detalls = models.TextField(blank=True, null=True)
    imatge = models.ImageField(upload_to='fotos_projecte_autoocupat_firaire')
    url_miniatura = models.CharField(max_length=1024, blank=True, null=True)

gestioci/apps/alta_socies/templates/alta_socies/autoocupat/00-acollida-identificacio_projecte.html
{% extends "alta_socies/autoocupat/template.html" %}
{% load gci_tags %}

{% block explicacio_pas %}
    <div class="panel">
        <ul>
            <li>Introduïu les dades del projecte que apareixen al full d'assistència de la sessió d'acollida.</li>
        </ul>
    </div>
{% endblock %}

{% block pas %}
    <fieldset>
        <legend>Sessió d'acollida</legend>
        {% form_field form.sessio_acollida hide_label=True %}
    </fieldset>

    <fieldset>
        <legend>Projecte</legend>
        <div class="row">
            <div class="medium-4 columns">
                {% form_field form.nom %}
            </div>
            <div class="medium-4 columns">
                {% form_field form.email %}
            </div>
            <div class="medium-4 columns">
                {% form_field form.telefon %}
            </div>
        </div>
    </fieldset>

    <button class="radius button" type="submit" name="anem_a" value="{{ ANEM_AQUI }}">Desar</button>
    <button class="radius button" type="submit" name="anem_a" value="{{ ANEM_SEGUENT }}">Desar i anar al següent pas</button>
{% endblock %}

gestioci/apps/alta_socies/templates/alta_socies/autoocupat/05-avaluacio-altres-activitats.html
{% extends "alta_socies/autoocupat/template.html" %}
{% load gci_tags %}

{% block explicacio_pas %}
    <div class="panel">
        <ul>
            <li>En el pas següent es podrà demanar que una o vàries assegurances cobreixin les adreces i les activitats.</li>
        </ul>
    </div>
{% endblock %}

{% block pas %}
    <fieldset>
        <legend>Altres activitats</legend>
        {% form_field form.altres_activitats hide_label=True %}
    </fieldset>

    <button class="radius button" type="submit" name="anem_a" value="{{ ANEM_AQUI }}">Desar</button>
    <button class="radius button" type="submit" name="anem_a" value="{{ ANEM_ANTERIOR }}">Desar i anar al pas anterior</button>
    <button class="radius button" type="submit" name="anem_a" value="{{ ANEM_SEGUENT }}">Desar i anar al següent pas</button>
{% endblock %}

gestioci/apps/alta_socies/templates/alta_socies/autoocupat/11-alta-cessions_us.html
{% extends "alta_socies/autoocupat/template.html" %}
{% load gci_tags %}

{% block explicacio_pas %}
    <div class="panel">
        <ul>
            <li>Enregistreu els detalls que hi ha a la documentació que aporten els membres de referència.</li>
            <li>Si us plau, reviseu les observacions! Els membres de referència les tenen a la llista de tasques que va sortir de la sessió d'avaluació.</li>
            <li>En aquest formulari només es veuen les adreces per les quals s'havia demanat una cessió d'ús.</li>
        </ul>
    </div>
{% endblock %}

{% block pas %}
    {{ formset.management_form }}

    {% for form in formset %}
        <fieldset>
            {{ form.id }}

            <legend>Adreça &laquo;{{ form.instance.designacio }}&raquo;</legend>

            <div class="row">
                <div class="medium-6 columns">
                    <div class="row">
                        <div class="medium-6 columns">
                            {% form_field form.traspas_inici %}
                        </div>
                        <div class="medium-6 columns">
                            {% form_field form.traspas_final %}
                        </div>
                    </div>

                    <div class="field">
                        <label><span>Comentaris avaluació</span></label>
                        {% if form.instance.traspas_comentaris_avaluacio %}
                            <p>
                                <em>{{ form.instance.traspas_comentaris_avaluacio|linebreaksbr }}</em>
                            </p>
                        {% else %}
                            <p class="color-warning">
                                <em>No es van deixar comentaris a la llista de tasques</em>
                            </p>
                        {% endif %}
                    </div>
                </div>
                <div class="medium-6 columns">
                    {% form_field form.traspas_comentaris_alta %}
                </div>
            </div>
        </fieldset>
    {% endfor %}

    <button class="radius button" type="submit" name="anem_a" value="{{ ANEM_AQUI }}">Desar</button>
    <button class="radius button" type="submit" name="anem_a" value="{{ ANEM_ANTERIOR }}">Desar i anar al pas anterior</button>
    <button class="radius button" type="submit" name="anem_a" value="{{ ANEM_SEGUENT }}">Desar i anar al següent pas</button>
{% endblock %}

gestioci/apps/alta_socies/templates/alta_socies/autoocupat/document-llista_de_tasques.html
<!DOCTYPE html>
<html>
<head lang="ca">
    <meta charset="UTF-8">
    <title>Llista de tasques</title>

<style>
    body {
        font-family: 'DejaVu Sans Condensed', sans-serif;
        font-size: 10pt;
        width: 190mm;
    }
    .capcalera {
        width: 100%;
        font-size: 130%;
        font-weight: bold;
        border-collapse: collapse;
        padding: 1mm;
    }
    .capcalera th {
        border: 1mm solid black;
        background-color: #d0d0d0;
    }
    .capcalera td {
        border: 1mm solid black;
        background-color: #dddddd;
        font-size: 120%;
    }
    .al { text-align: left; }
    .ac { text-align: center; }
    .ar { text-align: right; }
    .mitja_amplada { width: 50%; }
    .taula_informativa {
        width: 100%;
        border-collapse: collapse;
    }
    .taula_informativa th {
        border: 0.5mm solid black;
        background-color: #dddddd;
        font-size: 80%;
    }
    .taula_informativa td {
        border: .5mm solid black;
        font-style: italic;
        font-size:70%;
    }
    .peu td {
        border-top: 0.5mm solid black;
        font-size: 80%;
    }
    .url {
        font-family: monospace;
        text-decoration: none;
    }
    h1 {
        font-size:120%;
    }
    .llista_tasques {
        list-style: none;
    }

    {# mentre no investiguem com assegurar que no es trenquen els apartats a final de pàgina #}
    {# val mes que no separem la pàgina en dos; no sigui que algú faci només les tasques de la primera pàgina :) #}
{#    @media all {#}
{#	    .page-break	{ display: none; }#}
{#    }#}
{##}
{#    @media print {#}
{#	    .page-break	{ display: block; page-break-before: always; }#}
{#    }#}

    @page {
        size: A4 portrait;
        margin: 2cm;
    }
</style>
</head>
<body>
<table class="capcalera">
    <tr>
        <th class="ac">Cooperativa Integral Catalana &mdash; Procés d'alta de projecte autoocupat</th>
    </tr>
    <tr>
        <td class="ac">Llista de tasques pendents</td>
    </tr>
</table>

<p> A continuació, us indiquem la llista de tasques que heu de realitzar. Per qualsevol dubte disposeu de la pàgina web
    de la CIC<sup>1</sup>. En cas necessari, també podeu acudir al responsable amb qui heu fet la sessió d'Avaluació.
    Quan tingueu totes aquestes tasques completades haureu de demanar hora amb aquest responsable per venir un altre
    dia — les mateixes persones — a completar el procés d'alta del vostre projecte. IMPORTANT: si no aporteu tota la
    documentació i tasques demanades en aquesta llista no podrem completar el procés encara que vingueu a una sessió
    d'Alta, i l'haureu de repetir un altre dia.
</p>

<table class="taula_informativa">
	<tr>
        <th>Projecte</th><th>Responsable d'alta</th><th>Correu de contacte</th>
    </tr>
	<tr>
        <td class="ac">{{ proces.nom }}</td>
        <td class="ac">{{ user.first_name }}&nbsp;{{ user.last_name }}{{ proces.responsable.nom_public }}</td>
        <td class="ac">{{ user.email }}{{ proces.responsable.persona.email }}</td>
    </tr>
</table>


{% if traspassos %}
	<h1>Traspassos</h1>
	<table class="taula_informativa">
		<tr>
			<th>Tipus</th>
            <th>Adreça</th>
            <th>Comentaris</th>
		</tr>
		{% for traspas in traspassos %}
		<tr>
			<td class="ac">{{ traspas.tipus|safe }}</td>
			<td class="ac">
                {% if traspas.adreca %}
                    {{ traspas.adreca.adreca }} ({{ traspas.adreca.poblacio }})
                {% else %}
                    {{ NO_APLICA }}
                {% endif %}
            </td>
			<td class="ac">{{ traspas.comentaris }}</td>
		</tr>
		{% endfor %}
	</table>
	<p>Haureu d'aportar el document corresponent a cada traspàs.</p>
{% endif %}

{% if concessions %}
	<h1>Concessions d'activitats</h1>
	<table class="taula_informativa">
		<tr>
			<th>Activitat</th>
            <th>Adreça</th>
            <th>Comentaris</th>
		</tr>
		{% for concessio in concessions %}
		<tr>
			<td class="ac">{{ concessio.activitat }}</td>
            <td class="ac">
                {% if concessio.adreca %}
                    {{ concessio.adreca.adreca }} ({{ concessio.adreca.poblacio }})
                {% else %}
                    {{ NO_APLICA }}
                {% endif %}
            </td>
			<td class="ac">{{ concessio.comentaris }}</td>
		</tr>
		{% endfor %}
	</table>
	<p>Haureu d'aportar la llicència d'activitat i el contracte de concessió corresponents a cada activitat.</p>
{% endif %}

{% if assegurances_adreca or assegurances_altres_activitats %}
	<h1>Assegurances</h1>
	<table class="taula_informativa">
		<tr>
            <th>Activitat</th>
			<th>Adreça</th>
            <th>Comentaris</th>
		</tr>
		{% for ass in assegurances_adreca %}
            <tr>
                <td class="ac">
                    {% if ass.activitat.nom %}
                        {{ ass.activitat.nom }}
                    {% else %}
                        {{ NO_APLICA }}
                    {% endif %}
                </td>
                <td class="ac">
                    {{ ass.adreca.adreca }} ({{ ass.adreca.poblacio }})
                </td>
                <td class="ac">{{ ass.comentaris }}</td>
            </tr>
        {% endfor %}
		{% for ass in assegurances_altres_activitats %}
            <tr>
                <td class="ac">
                    {% if ass.activitat.nom %}
                        {{ ass.activitat.nom }}
                    {% else %}
                        {{ NO_APLICA }}
                    {% endif %}
                </td>
                <td class="ac">
                    {% if ass.adreca %}
                        {{ ass.adreca.adreca }} ({{ ass.adreca.poblacio }})
                    {% else %}
                        {{ NO_APLICA }}
                    {% endif %}
                </td>
                <td class="ac">{{ ass.comentaris }}</td>
            </tr>
        {% endfor %}
	</table>
	<p>Haureu d'aportar el rebut vigent i el certificat de cobertura corresponents a cada assegurança.</p>
{% endif %}

<div class="page-break"></div>

{% if proces.tipus == proces.TIPUS_AUTOOCUPAT_FIRAIRE %}
<h1>Firaires</h1>
<ul class="llista_tasques">
    <li>&#x2611;&nbsp;Foto de la parada</li>
    <li>&#x2611;&nbsp;Fotos dels productes i/o gammes de productes</li>
    <li>&#x2611;&nbsp;Descripció detallada de la parada i els productes</li>
</ul>
<p>Porteu les fotos i descripcions en USB, o adjunteu-les a un correu electrònic al vostre responsable.</p>
{% endif %}

<h1>Quotes</h1>
<ul class="llista_tasques">
    <li>&#x2611;&nbsp;Quota d'alta:
        {{ proces.quota_alta_quantitat }}&nbsp;{{ proces.get_quota_alta_forma_pagament_display }}</li>
    <li>&#x2611;&nbsp;Quota trimestral avançada:
        {{ proces.quota_avancada_quantitat }}&nbsp;{{ proces.get_quota_avancada_forma_pagament_display }}</li>
</ul>
<p>Si les quotes es paguen en moneda social caldrà portar el número d'un compte CES que ja tingueu.</p>

{% if proces.individual == proces.INDIVIDUAL_COL_LECTIU %}
<h1>Socis afins</h1>
<ul class="llista_tasques">
    <li>&#x2611;&nbsp;Portar apuntats els nom, cognom i DNI de tots socis afins del projecte.</li>
</ul>
<p>Són socis afins els membres de referència, i també els membres que vulguin rebre cobertura legal de la CIC.</p>
{% endif %}

<table class="peu">
    <tr>
        <td>
        	<sup>1</sup>&nbsp;<a class="url" href="http://cooperativa.cat/participa/vols-fer-ten-soci-autonom/">http://cooperativa.cat/participa/vols-fer-ten-soci-autonom/</a>
		</td>
	</tr>
</table>
</body>
</html>

gestioci/apps/alta_socies/templates/alta_socies/autoocupat/template.html
{% extends "layout.html" %}

{% block titol_a_capcalera %}Procés d'alta de projecte autoocupat{% endblock %}

{% block content %}
    <div class="row">
        <div class="medium-12 columns content">
            <div class="row">
                <div class="medium-12 columns" style="text-align: center;">
                    <ul class="steps">
                        {% for p in breadcrumbs %}
                            <li>
                                <a  data-tooltip
                                    {% if p.n <= proces.pas_maxim_assolit and id_proces %}
                                        href="{% url "alta_socies:proces_alta_projecte_autoocupat" id_proces p.n %}"
                                    {% endif %}
                                    class="
                                        radius tip-bottom
                                        {% if p.n == pas %}
                                            current
                                        {% endif %}
                                        {% if p.n < proces.pas %}
                                            done
                                        {% elif p.n <= proces.pas_maxim_assolit %}
                                            to-review
                                        {% else %}
                                            disabled
                                        {% endif %}
                                        {# TODO: Separación entre sesiones hardcoded… ejem… #}
                                        {% if p.n == 2 or p.n == 10 or p.n == 11 %}
                                            divider
                                        {% endif %}
                                    "
                                    aria-haspopup="true"
                                    title="{{ p.nom }}"
                                >
                                    {{ p.n }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="medium-12 columns content">
            <div class="row">
                <div class="medium-12 columns">
                    <h1>{{ nom_pas }}</h1>
                    {% block explicacio_pas %}{% endblock %}
                    <form method="post"
                        {% if id_proces %}
                            action="{% url "alta_socies:proces_alta_projecte_autoocupat" id_proces pas %}"
                        {% else %}
                            action="{% url "alta_socies:proces_alta_projecte_autoocupat" %}"
                        {% endif %}
                    >
                        {% csrf_token %}
                        {% block pas %}{% endblock %}
                    </form>
                    {% block pas_formularis_addicionals %}{% endblock %}
                </div>
            </div>
        </div>
    </div>
{%  endblock %}