gestioci/apps/alta_socies/urls.py
from django.conf.urls import patterns, include, url

from .views import SessioMonedaListView, SessioMonedaCreateView
from .views import SessioAcollidaListView, SessioAcollidaCreateView, \
    SessioAcollidaUpdateView, SessioMonedaUpdateView
from .views import ProcesAltaAutoocupatDetailView

urlpatterns = patterns(

    'gestioci.apps.alta_socies.views',

    # -----------------
    # SOCIS AUTOOCUPATS
    # -----------------

    url(r'^rebutjar_proces_alta/(?P<proces_id>\d+)/$', 'rebutjar_proces_alta_autoocupat', name='rebutjar_proces'),

    url(r'^exportar_a_csv/$', 'exportar_a_csv', name='exportar_a_csv'),

    url(r'^autoocupat/resum/(?P<pk>\d+)/$', ProcesAltaAutoocupatDetailView.as_view(), name='resum_proces_alta_projecte_autoocupat'),

    url(r'^editar_sessio_moneda/(?P<pk>\d+)/$', SessioMonedaUpdateView.as_view(), name='editar_sessio_moneda'),

    url(r'^editar_sessio_acollida/(?P<pk>\d+)/$', SessioAcollidaUpdateView.as_view(), name='editar_sessio_acollida'),

    url(r'^llistat_sessio_acollida', SessioAcollidaListView.as_view(), name='llistat_sessio_acollida'),

    url(r'^crear_sessio_acollida', SessioAcollidaCreateView.as_view(), name='crear_sessio_acollida'),

    url(r'^llistat_sessio_moneda', SessioMonedaListView.as_view(), name='llistat_sessio_moneda'),

    url(r'^crear_sessio_moneda', SessioMonedaCreateView.as_view(), name='crear_sessio_moneda'),

    url(r'^generador_sessions/$',
        'generar_sessions',
        name='generador_sessions'),

    url(r'^sessions_del_mes/(?P<tipus>\w+)(/(?P<year>\d\d\d\d)/(?P<month>\d\d?))?$',
        'sessions_del_mes',
        name='sessions_del_mes'),

    url(r'^autoocupat/$',
        'proces_alta_projecte_autoocupat',
        name='proces_alta_projecte_autoocupat'),

    url(r'^autoocupat/(?P<id_proces>\d+)/$',
        'proces_alta_projecte_autoocupat',
        name='proces_alta_projecte_autoocupat'),

    url(r'^autoocupat/(?P<id_proces>\d+)/(?P<pas>\d+)/$',
        'proces_alta_projecte_autoocupat',
        name='proces_alta_projecte_autoocupat'),

    url(r'^autoocupat/llista-tasques/(?P<id_proces>\d+)/$',
        'proces_alta_projecte_autoocupat_llista_de_tasques',
        name='proces_alta_projecte_autoocupat-llista_de_tasques'),

    url(r'^autoocupat/llista-tasques/(?P<id_proces>\d+)/(?P<format>pdf|html)/$',
        'proces_alta_projecte_autoocupat_llista_de_tasques',
        name='proces_alta_projecte_autoocupat-llista_de_tasques'),

    url(r'^autoocupat/processos/(?P<estat>\w+)/$',
        'llistat_proces_alta_projecte_autoocupat',
        name='llistat_proces_alta_projecte_autoocupat'),

    url(r'^autoocupat/processos/(?P<estat>\w+)/tots$',
        'llistat_proces_alta_projecte_autoocupat', {'filtre_responsable': False},
        name='llistat_proces_alta_projecte_autoocupat-tots'),

    url(r'^autoocupat/control-qualitat/$',
        'llistat_proces_alta_projecte_autoocupat_revisio_descripcions',
        name='llistat_proces_alta_projecte_autoocupat_revisio_descripcions'),

    url(r'^estadistiques_proces_alta_projecte_autoocupat/?$',
        'estadistiques_proces_alta_projecte_autoocupat',
        name='estadistiques_proces_alta_projecte_autoocupat'),

    # -----------------
    # SOCIS COOPERATIUS
    # -----------------
    url(r'^cooperatiu/$', 'cooperatiu', name='cooperatiu'),
)

gestioci/apps/inici/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'gestioci.apps.inici.views',

    url(r'^/?$',           'index',      name='index'),
    url(r'^style-guide/$', 'styleguide', name='styleguide'),
)

gestioci/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = patterns(
    '',

    # Default Django Auth
    # https://docs.djangoproject.com/en/1.8/topics/auth/default/#built-in-auth-views
    url(r'^accounts/', include([
        url(r'^login/$', auth_views.login, name='login'),
        url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),

        url(r'^password/', include([
            url(r'^change/$', auth_views.password_change, name='password_change'),
            url(r'^change/done/$', auth_views.password_change_done, name='password_change_done'),

            url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
            url(r'^reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),
            url(r'^reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
            url(r'^reset/$', auth_views.password_reset, { 'html_email_template_name': 'registration/password_reset_email.html' }, name='password_reset'),
        ])),
    ])),


    # Apps
    url(r'^',             include('gestioci.apps.inici.urls', namespace='inici')),
    url(r'^socies/alta/', include('gestioci.apps.alta_socies.urls', namespace='alta_socies')),
    url(r'^socies/',      include('gestioci.apps.socies.urls', namespace='socies')),
    url(r'^facturacio/',  include('gestioci.apps.facturacio.urls', namespace='facturacio')),
    
    url(r'^admin/',       include(admin.site.urls)),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns(
        '',
        (
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

gestioci/apps/inici/models.py
from django.db import models

# Create your models here.

gestioci/apps/inici/views.py
# coding=utf-8
from django.contrib import messages
from django.shortcuts import render


def index(request):
    return render(request, 'inici/index.html', {
        'page_title': u'Inici',
    })


def styleguide(request):
    from django import forms

    choice_list = (('', 'Select…'), ('foo', 'Foo'), ('bar', 'Bar'), ('baz', 'Baz'), ('qux', 'Qux'))

    class Form(forms.Form):
        name = forms.CharField(label='Nombre', max_length=100)
        email = forms.EmailField(label='Email', required=False, help_text='This is a help text.')
        boolean = forms.BooleanField(label='Boolean', required=False)
        accept = forms.BooleanField(label='Boolean')
        choices = forms.ChoiceField(label='Choices', choices=choice_list)
        radiuses = forms.ChoiceField(label='Radius', choices=choice_list, widget=forms.RadioSelect)
        multiple = forms.MultipleChoiceField(label='Multiple Choices', choices=choice_list, initial=('foo', 'baz'))
        multicheck = forms.MultipleChoiceField(label='Checkboxes', choices=choice_list, widget=forms.CheckboxSelectMultiple)
        date = forms.DateField(label='Date', widget=forms.DateInput, initial='2015-05-01')
        time = forms.TimeField(label='Time', widget=forms.TimeInput, initial='15:20')
        datetime = forms.DateTimeField(label='Datetime', widget=forms.SplitDateTimeWidget)

    messages.info(request, 'Three credits remain in your account.')
    messages.success(request, 'Profile details updated.')
    messages.warning(request, 'Your account expires in three days.')
    messages.error(request, 'Document deleted.')

    return render(request, 'inici/styleguide.html', {
        'forms': {
            'A':               Form(),
            'B (POST Errors)': Form(request.POST)
        },
        'page_title': u'Style Guide',
    })

gestioci/apps/inici/templates/inici/index.html
{% extends "layout.html" %}
{% load gci_tags %}
{% block content %}
    <div class="row">
        <div class="medium-12 columns">
            <div class="groups-container" data-masonry>
                {% if user.is_authenticated %}
                    {% if user|is_responsable_alta %}
                    <section class="group">
                        <div class="content">
                            <h1><i class="fa fa-fw fa-users"></i> Altes de projecte autoocupat</h1>
                            <ul class="radius button-group even-2">
                                <li>
                                    <a href="{% url "alta_socies:proces_alta_projecte_autoocupat" %}" class="button">
                                        <i class="fa fa-fw fa-plus"></i> Nova alta
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url "alta_socies:llistat_proces_alta_projecte_autoocupat" 'en_curs' %}" class="button">
                                        <i class="fa fa-fw fa-tasks"></i> En curs
                                    </a>
                                </li>
                            </ul>
                            <ul class="radius button-group even-2">
                                <li>
                                    <a href="{%  url "alta_socies:llistat_proces_alta_projecte_autoocupat_revisio_descripcions" %}" class="button">
                                        <i class="fa fa-fw fa-check"></i> Control de qualitat
                                    </a>
                                </li>
                                <li>
                                    <a href="{%  url "alta_socies:estadistiques_proces_alta_projecte_autoocupat" %}" class="button">
                                        <i class="fa fa-fw fa-check"></i> Estadístiques
                                    </a>
                                </li>
                            </ul>
                            {% if user|is_exportador %}
                            <ul class="radius button-group even-1">
                                <li>
                                    <a href="{% url "alta_socies:exportar_a_csv" %}" class="button">
                                        <i class="fa fa-fw fa-level-down"></i> Exportar al «Transversal»
                                    </a>
                                </li>
                            </ul>
                            {% endif %}
                        </div>
                    </section>
                    <section class="group">
                        <div class="content">
                            <h1><i class="fa fa-fw fa-calendar"></i> Sessions</h1>
                            <ul class="radius button-group even-3">
                                <li>
                                    <a href="#" class="disabled info button">Acollida</a>
                                </li>
                                <li>
                                    <a href="{% url "alta_socies:crear_sessio_acollida" %}" class="button"><i class="fa fa-fw fa-plus"></i> Nova</a>
                                </li>
                                <li>
                                    <a href="{% url "alta_socies:llistat_sessio_acollida" %}" class="button"><i class="fa fa-fw fa-bars"></i> Llistat</a>
                                </li>
                            </ul>
                            <ul class="radius button-group even-3">
                                <li>
                                    <a href="#" class="disabled info button">Moneda social</a>
                                </li>
                                <li>
                                    <a href="{% url "alta_socies:crear_sessio_moneda" %}" class="button"><i class="fa fa-fw fa-plus"></i> Nova</a>
                                </li>
                                <li>
                                    <a href="{% url "alta_socies:llistat_sessio_moneda" %}" class="button"><i class="fa fa-fw fa-bars"></i> Llistat</a>
                                </li>
                            </ul>
                        </div>
                    </section>
                    {% endif %}
                {% endif %}
                {% if FLAG_GECO %}
                    {% if user.is_authenticated %}
                        {# TODO: show section only to socies AO #}
                        <section class="group green">
                            <div class="content">
                                <h1><i class="fa fa-fw fa-file-text-o"></i> Papeleos</h1>
                                <ul>
                                    <li><a href="#">Añadir factura</a></li>
                                    <li><a href="#">Añadir gasto</a></li>
                                    <li>…</li>
                                </ul>
                            </div>
                        </section>
                        {# TODO: show section only to GECO admins #}
                        <section class="group green">
                            <div class="content">
                                <h1><i class="fa fa-fw fa-money"></i> Gestió Económica</h1>
                                <p>…</p>
                            </div>
                        </section>
                    {% endif %}
                {% endif %}
                {% if FLAG_ALTA_SOCIES %}
                    {% if not user.is_authenticated %}
                        <section class="group">
                            <div class="content">
                                <h1><i class="fa fa-fw fa-pencil"></i> Fes-te soci@ de la CIC</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                consequat.</p>
                                <p>
                                    <a href="{% url 'alta_socies:cooperatiu' %}" class="radius button expand">Formulari de inscripció soci cooperatiu</a>
                                </p>
                                <hr/>
                                <h2>Quieres hacerte socio autoocupado?</h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                consequat.</p>
                            </div>
                        </section>
                    {% endif %}
                {% endif %}
                {% if FLAG_FAQ %}
                    {% if not user.is_authenticated %}
                        <section class="group">
                            <div class="content">
                                <h1><i class="fa fa-fw fa-flag"></i> Bienvenido al portal del socio!</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                consequat.</p>
                            </div>
                        </section>
                    {% endif %}
                    <section class="group blue">
                        <div class="content">
                            <h1><i class="fa fa-fw fa-question-circle"></i> FAQs</h1>
                            <input type="text" placeholder="Buscar…">
                        </div>
                    </section>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}